### ISSUE TITLE
[feature-request] Allow to set git push options

### ISSUE THREAD

**Issue by ekle** [go-semantic-release/provider-git#6]
It would be useful, if there would be a option to provide `git push -o` options as a config.

gitlab is using push options for some CI features which would simplify my pipeline. (https://docs.gitlab.com/ee/user/project/push_options.html)

**Comment by ekle** [comment]
created a pull request for that feature: https://github.com/go-semantic-release/provider-git/pull/7

**Comment by christophwitzko** [comment]
Thanks for this! ✨
